version: '3.9'

services:
  database:
    image: postgres
    container_name: biopark_backend
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
